### ISSUE TITLE
Questions regarding the mask_fn

### ISSUE THREAD

**Issue by hui-po-wang** [google-deepmind/language_modeling_is_compression#10]
Dear authors,

Thanks so much for the amazing work! 

I have some questions regarding the mask function. During compression, you used a mask function to pre-process data. For instance, a [right_shift_bytes_by_one](https://github.com/google-deepmind/language_modeling_is_compression/blob/main/utils.py#L42) function is used to shift the chunked data by 1 bit.

I wonder what's the purpose of it, and is it still a lossless compression even if the LSB is discarded?

Thanks for your time.

**Comment by anianruoss** [comment]
We describe this in detail in appendix B.2 of our [ICLR 2024 paper](https://openreview.net/pdf?id=jznbgiynus). Please let me know if you have any further questions.

**Comment by anianruoss** [comment]
Also, see https://x.com/anianruoss/status/1704615421280649436

**Comment by anianruoss** [comment]
But you are right: If you want to implement a truly lossless compressor, you'll have to account for the masked bit. We do this when computing the compression rate.
