### ISSUE TITLE
Applying tokenizers before compression

### ISSUE THREAD

**Issue by hui-po-wang** [google-deepmind/language_modeling_is_compression#11]
Dear authors,

Thanks so much for the interesting work!

I am currently trying to replace the language models in your code with GPT-2; however, it seems that the encoding after tokenization is not as impressive as the results you showed in the paper. I wonder if your finding only applies to pure ASCII (i.e., w/o tokenization) regarding image compression.

I also noticed that in Table 2, you tested different sizes of BPE on a text dataset. I wonder if you have any results on images?

Thanks so much for your time. I'd appreciate any feedback you may have.

best,

**Comment by anianruoss** [comment]
I don't quite understand your question "your finding only applies to pure ASCII" regarding image compression. We tokenized the images by converting them to grayscale, flattening them, and then converting those bytes to ASCII such that non-multimodal LLMs such as Chinchilla would be able to process them.

We did not investigate BPE on image datasets.

**Comment by hui-po-wang** [comment]
Hi @anianruoss ,

Thanks for the answer, and sorry for the confusion. I am actually just curious about your opinions on whether your findings can be generalized when using pre-trained text tokenizers for other modalities, such as images. 

I am currently trying to compress images using GPT -2 but have failed to reproduce the performance or even match the PNG codec. Given that, I am curious if tokenization would be the main cause of the failure.

best,

**Comment by anianruoss** [comment]
I don't know if tokenization is the cause of failure. We implemented a pretty naive tokenization and it worked well.
