### ISSUE TITLE
Request for implementation of Llama2 compression

### ISSUE THREAD

**Issue by richardChenzhihui** [google-deepmind/language_modeling_is_compression#14]
First of all, thanks for the insightful work.  It would be good if the authors release the relevant implementation of the llama2 compressor.

**Comment by anianruoss** [comment]
Thank you for your interest in our work, @richardChenzhihui!

Unfortunately, we will not be releasing our implementation of the Llama 2 compressor. However, it should be as simple as replacing the `predict_fn` in `compressors/language_model.py`
