### ISSUE TITLE
Request for Training Steps and Transformer Configurations

### ISSUE THREAD

**Issue by vonpetersenn** [google-deepmind/language_modeling_is_compression#15]
Hello,

for the sake of reproducing the result from your fantastic paper, I would like to ask if you could share the number of `training_steps` (referencing `train.py`) you used to train the transformer to achieve a compression rate of 30.9?

I would also like to confirm if my understanding is correct that the transformer in question is the model you refer to in your paper as _Transformer 200K_?
If so, could you please provide the parameters you used in the `TransformerConfig` class for the 800K and 3.2M transformers?

Thank you,

Paulo

**Comment by anianruoss** [comment]
Hi Paulo,

Thank you for your interest in our paper!

Here are the configs:

200K
```
{
  "training_steps": "1000000",
  "batch_size": "32",
  "seq_length": "2048",
  "embedding_dim": "64",
  "num_heads": "4",
  "num_layers": "4",
  "positional_encodings": "ROTARY",
}
```

800K
```
{
  "training_steps": "1000000",
  "batch_size": "32",
  "seq_length": "2048",
  "embedding_dim": "128",
  "num_heads": "4",
  "num_layers": "4",
  "positional_encodings": "ROTARY",
}
```

3.2M
```
{
  "training_steps": "1000000",
  "batch_size": "32",
  "seq_length": "2048",
  "embedding_dim": "256",
  "num_heads": "8",
  "num_layers": "4",
  "positional_encodings": "ROTARY",
}
```
