### ISSUE TITLE
How does the arithmetic coder handle a top_k miss for Llama?

### ISSUE THREAD

**Issue by francisrmatt** [google-deepmind/language_modeling_is_compression#17]
I previously wrote an issue about Llama tokenisation but have since closed it as it did not quite explain where my confusion lay.

In appendix B.2. you write that the input sequence is tokenised to length l with T possible tokens, with a total of l*T log-probabilities. You note that while it is possible to have such a massive alphabet size, in reality, you take the top 100 log-probabilities and use that as the alphabet for the next sequence in the arithmetic coder.

My question is then - what if the top 100 log probabilities do not include the actual next token? What is then put into the arithmetic coder. It is noted in the paper that k=100 'almost fully recovers the conditional distribution'. I am interested in the case where it doesn't and how you dealt with that, and subsequently if there was a miss how you went on to decompress the data.

Thanks

**Comment by anianruoss** [comment]
For the purposes of our experiments, the tokens were always within the top 100. If your token is not, you will have to increase `k` accordingly.
