### ISSUE TITLE
can not decompress

### ISSUE THREAD

**Issue by ChrisZhangyu** [google-deepmind/language_modeling_is_compression#20]
For large models such as llama, the probabilities generated by inputting sequences one by one and inputting all sequences at once are inconsistent, which will lead to decoding problems. How to solve this problem? In your code, if I do not use use_slow_lossless_compression, the probabilities when encoding and decoding will be inconsistent.

**Comment by anianruoss** [comment]
Indeed, using `use_slow_lossless_compression` is the way to deal with this numerical issue.

**Comment by xiaojxkevin** [comment]
> For large models such as llama, the probabilities generated by inputting sequences one by one and inputting all sequences at once are inconsistent, which will lead to decoding problems. How to solve this problem? In your code, if I do not use use_slow_lossless_compression, the probabilities when encoding and decoding will be inconsistent.

Hi, sorry for bothering. I am wondering can you decompress the message correctly with the use of `use_slow_lossless_compression`? The current experiment of mine #21 shows that we cannot decompress. Thus I am wondering what's the result from your side.
Thanks in advance!
