### ISSUE TITLE
how to reproduce with a pre-trained llm?

### ISSUE THREAD

**Issue by zhu-zaifei** [google-deepmind/language_modeling_is_compression#6]
hi , thank you for this great idea to  link llm and data compression!

I'm going to reproduce the result of your paper,  with a pretrained llm, somthing like Chinchilla-70B or GPT4 which is pre-trained. 
idealy, I want reproduce a compression rate about 8.3. 

Can you kindly advice on how to proceed ? If I skip the training phase,  I will not have a  params.npz,  should I go deep through the npz file  to make LLM generate an alternative one ?

thanks,

**Comment by anianruoss** [comment]
All you need is to do is to replace the `predict_fn` on L138 of `compressors/language_model.py`.
