### ISSUE TITLE
is it possible to release your params.npz used in the paper?

### ISSUE THREAD

**Issue by zhu-zaifei** [google-deepmind/language_modeling_is_compression#7]
Hi  Anianruoss,

I'm doing the local training to reproduce your result with a tiny lm. it took hours to do the training in a AWS EC2 host with GPU which cost is ~10$. the cost to train  a Chinchilla 7B will be crazy expensive .....

Is it possible to release  your params.npz used in the paper?   If yes, we can skip the training phase and jump to the reproducing much quickly.   just need some more  compression   to see if any more training should go.

thanks,

**Comment by anianruoss** [comment]
Yes, training a Chinchilla-like model is very expensive, which is why we cannot release the weights, unfortunately. However, we just added results with LLaMA1, which is open-source, to the paper and they are comparable to the Chinchilla results.
