### ISSUE TITLE
Paper now has Llama1-7b results, will you update the code?

### ISSUE THREAD

**Issue by atiorh** [google-deepmind/language_modeling_is_compression#8]
Hey @anianruoss  @fazega! The version of the paper on OpenReview now has Llama1-7b results, will you update the code? https://openreview.net/pdf?id=jznbgiynus

**Comment by fazega** [comment]
We are working on it.

**Comment by adnan1306** [comment]
Hi authors! I'm trying to implement your code using Llama for encoding. I have a quick question --- do you change the default tokenizer and vocab? I see in the transformer.py file the output vocab is 0-255, how did you handle tokenization with Llama!

**Comment by FractureSR** [comment]
> Hi authors! I'm trying to implement your code using Llama for encoding. I have a quick question --- do you change the default tokenizer and vocab? I see in the transformer.py file the output vocab is 0-255, how did you handle tokenization with Llama!

Hi adnan1306. I'm also reproduing the work by replacing the probability generator with llama2 and llama3. Have you achieved satisfying compression preformance in your implementation? or do you know any repo which reproduces the preformance in the paper?

**Comment by anianruoss** [comment]
Thank you for your interest in our work!

Unfortunately, we will not be releasing our implementation of the Llama 2 compressor. However, it should be as simple as replacing the `predict_fn` in `compressors/language_model.py`. We used Llama's default tokenizer.
